apiVersion: batch/v1
kind: CronJob
metadata:
  name: simple-cron1
  generateName: kube-job-
# namespace: prod
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:      
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["echo", "Kubernetes Job"]
          restartPolicy: OnFailure
